version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      POSTGRESQL_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRESQL_USERNAME: ${DB_POSTGRES_USER}
      POSTGRESQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_POSTGRES_PORT}:5432
    volumes:
      - pgdata:/data/postgres

  mongodb:
    image: bitnami/mongodb:latest
    restart: always
    environment:
      MONGODB_PASSWORD: ${DB_MONGO_PASSWORD}
      MONGODB_USERNAME: ${DB_MONGO_USER}
      MONGODB_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_MONGO_PORT}:27017
    volumes:
      - mgdata:/data/mongodb

  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: ${DB_REDIS_PASSWORD}
    ports:
      - ${DB_REDIS_PORT}:6379
    volumes:
      - rsdata:/data/redis

  # roteiro:
  #   container_name: roteiro
  #   build: .
  #   restart: always
  #   ports:
  #     - ${APP_API_PORT}:${APP_API_PORT}
  #     - 9229:9229
  #   volumes:
  #     - .:/usr/app
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "5"
  #   links:
  #     - postgres
  #     - mongodb
  #     - redis
  #   depends_on:
  #     - postgres
  #     - mongodb
  #     - redis

volumes:
  pgdata:
    driver: local
  mgdata:
    driver: local
  rsdata:
    driver: local
